[versions]
# Plugins
kotlin = "2.0.0"
springBoot = "3.3.1"
springDependencyManagement = "1.1.6"
shadow = "8.1.1"
foojayResolver = "0.10.0"

# Dependencies
kotlinxCli = "0.3.6"
zip4j = "2.11.5"
kotlinxCoroutines = "1.8.1"
kotlinxSerializationCore = "1.7.1"
xmlutilSerialization = "0.91.1"
jsoup = "1.18.1"
ktor = "2.3.12"
webpImageio = "0.1.6"
slf4j = "2.0.13"

# Testing
kotlinTest = "2.0.0"

[libraries]
# Core
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli-jvm", version.ref = "kotlinxCli" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutilSerialization" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
webp-imageio = { module = "org.sejda.imageio:webp-imageio", version.ref = "webpImageio" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

# Ktor HTTP Client
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-plugins = { module = "io.ktor:ktor-client-plugins", version.ref = "ktor" }

# Spring Boot
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinTest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
shadow-jar = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojayResolver" }
