name: Build Release Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  # This is your existing job for desktop builds
  build-desktop:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew packageDistributionForCurrentOS cliJar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MangaCombiner-${{ matrix.os }}
          path: |
            build/compose/binaries/main/
            build/libs/*.jar
            
    build-android:
        needs: build-desktop
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '17'
          
          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@v3
    
          - name: Decode Keystore & Create Properties File
            run: |
              echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.keystore
              echo "storeFile=../my-release-key.keystore" > keystore.properties
              echo "storePassword=${{ secrets.RELEASE_STORE_PASSWORD }}" >> keystore.properties
              echo "keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}" >> keystore.properties
              echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> keystore.properties
    
          - name: Build Android App Bundle and APK
            run: ./gradlew bundleRelease assembleRelease
    
          - name: Upload Android App Bundle and APK
            uses: actions/upload-artifact@v4
            with:
              name: MangaCombiner-Android
              path: |
                build/outputs/bundle/release/*.aab
                build/outputs/apk/release/*.apk
