name: Build Release Packages

# This workflow runs when you push a tag that starts with 'v' (e.g., v1.0.0, v1.2.3)
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    # Use a matrix strategy to run the same steps on different OSes
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        # For Windows, the script is gradlew.bat, but the action handles this
        run: ./gradlew packageDistributionForCurrentOS cliJar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MangaCombiner-${{ matrix.os }}
          path: |
            build/compose/binaries/main/
            build/libs/*.jar
